Rework: Wait for DB

diff --git a/root/etc/s6-overlay/s6-rc.d/init-kanka-ce-config/run b/root/etc/s6-overlay/s6-rc.d/init-kanka-ce-config/run
--- a/root/etc/s6-overlay/s6-rc.d/init-kanka-ce-config/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-kanka-ce-config/run
@@ -10,24 +10,25 @@ if ! grep -qx '^post_max_size.*$' /config/php/php-local.ini; then
     echo 'post_max_size = 100M' >>/config/php/php-local.ini
 fi
 
-# if DB_PORT is not set
-if [[ -z "${DB_PORT}" ]]; then
-    DB_PORT="3306"
+ENV_FILE="/app/www/.env"
+if [ ! -f "$ENV_FILE" ]; then
+    echo "The configuration file is missing (.env)."
+    exit 1
+else
+    source "$ENV_FILE"
 fi
 
-# check for the mysql endpoint
-echo "Waiting for DB to be available"
-END=$((SECONDS + 30))
-while [[ ${SECONDS} -lt ${END} ]] && [[ -n "${DB_HOST+x}" ]]; do
-    if [[ $(/usr/bin/nc -w1 "${DB_HOST}" "${DB_PORT}" | tr -d '\0') ]]; then
-        if [[ ! -f /tmp/dbwait.lock ]]; then
-            sleep 5
-        fi
-        touch /tmp/dbwait.lock
-        break
-    else
-        sleep 1
-    fi
+echo "Waiting for database connection..."
+DB_HOST="${DB_HOST:-mysql}"
+DB_PORT="${DB_PORT:-3306}"
+DB_USERNAME="${DB_USERNAME:-kanka}"
+DB_PASSWORD="${DB_PASSWORD:-}"
+DB_DATABASE="${DB_DATABASE:-kanka}"
+
+while ! mariadb -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USERNAME" -p"$DB_PASSWORD" "$DB_DATABASE" \
+        -e "SELECT 1" >/dev/null 2>&1
+do
+    sleep 5
 done
 
 # One time setup
